library(data.table)
library(sqldf)
data<-read.csv.sql("household_power_consumption.txt",sep=";",header=TRUE,sql="select * from file where Date in ('1/2/2007','2/2/2007')")
closeAllConnections()
datetime<-as.POSIXct(paste(data$Date,data$Time),format="%d/%m/%Y %H:%M:%S")
newdata<-cbind(datetime,data)
finaldata<-subset(newdata,select=-c(Date,Time))
png(file="Plot2.png",width=480,height=480)
plot(finaldata$datetime,finaldata$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()
